-- 1. إنشاء الجداول الأساسية
CREATE TABLE projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  client_name TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  unit_type TEXT,
  unit_category TEXT,
  quantity INTEGER DEFAULT 1,
  width NUMERIC,
  height NUMERIC,
  depth NUMERIC,
  shelves_count INTEGER DEFAULT 0,
  drawers_count INTEGER DEFAULT 0,
  door_code_type TEXT,
  chassis_code_type TEXT,
  dummy_side TEXT,
  front_tape_color TEXT,
  has_glass_door BOOLEAN DEFAULT false,
  has_glass_shelf BOOLEAN DEFAULT false,
  notes TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE cutting_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE UNIQUE,
  assembly_system TEXT,
  handle_type TEXT,
  counter_thickness NUMERIC,
  mirror_width NUMERIC,
  back_deduction NUMERIC,
  depth_deduction NUMERIC,
  door_width_deduction NUMERIC,
  door_height_deduction_ground NUMERIC,
  wood_price NUMERIC,
  glass_price NUMERIC,
  basic_code TEXT,
  extra_code1 TEXT,
  extra_code2 TEXT,
  front_tape_basic TEXT,
  front_tape_extra TEXT,
  hinge_height NUMERIC,
  hinge_drop NUMERIC,
  drawer_depth NUMERIC,
  drawer_height NUMERIC,
  drawer_thickness NUMERIC,
  handle_cut_width NUMERIC,
  handle_cut_depth NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE accessories_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT,
  unit_price NUMERIC,
  quantity INTEGER,
  total_price NUMERIC,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE boards_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  board_type TEXT,
  thickness NUMERIC,
  color TEXT,
  price NUMERIC,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE app_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE users_profile (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  role TEXT DEFAULT 'user',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. إيقاف RLS (Row Level Security) مؤقتاً لتسهيل عمل الـ API الحالية (لكونها تستخدم service_role أو مصممة للعمل المباشر)
-- ملاحظة: في بيئة الإنتاج المتقدمة يُفضل تفعيلها ووضع سياسات (Policies) للحماية.
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE units DISABLE ROW LEVEL SECURITY;
ALTER TABLE cutting_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE accessories_prices DISABLE ROW LEVEL SECURITY;
ALTER TABLE boards_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE users_profile DISABLE ROW LEVEL SECURITY;
