-- 1. إنشاء الجداول الأساسية (إذا لم تكن موجودة)
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id),
  name TEXT NOT NULL,
  client_name TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  unit_type TEXT,
  unit_category TEXT,
  quantity INTEGER DEFAULT 1,
  width NUMERIC,
  height NUMERIC,
  depth NUMERIC,
  shelves_count INTEGER DEFAULT 0,
  drawers_count INTEGER DEFAULT 0,
  door_code_type TEXT,
  chassis_code_type TEXT,
  dummy_side TEXT,
  front_tape_color TEXT,
  has_glass_door BOOLEAN DEFAULT false,
  has_glass_shelf BOOLEAN DEFAULT false,
  notes TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS cutting_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE UNIQUE,
  assembly_system TEXT,
  handle_type TEXT,
  counter_thickness NUMERIC,
  mirror_width NUMERIC,
  back_deduction NUMERIC,
  depth_deduction NUMERIC,
  door_width_deduction NUMERIC,
  door_height_deduction_ground NUMERIC,
  wood_price NUMERIC,
  glass_price NUMERIC,
  basic_code TEXT,
  extra_code1 TEXT,
  extra_code2 TEXT,
  front_tape_basic TEXT,
  front_tape_extra TEXT,
  hinge_height NUMERIC,
  hinge_drop NUMERIC,
  drawer_depth NUMERIC,
  drawer_height NUMERIC,
  drawer_thickness NUMERIC,
  handle_cut_width NUMERIC,
  handle_cut_depth NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS accessories_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT,
  category TEXT,
  unit TEXT,
  unit_price NUMERIC,
  quantity NUMERIC DEFAULT 1,
  notes TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS boards_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  board_name TEXT,
  code TEXT,
  width NUMERIC,
  height NUMERIC,
  thickness NUMERIC,
  price_per_board NUMERIC,
  cutting_cost_per_cut NUMERIC,
  edge_tape_cost_per_meter NUMERIC,
  notes TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS app_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS users_profile (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  role TEXT DEFAULT 'user',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. تحديث الجداول الموجودة (إضافة الأعمدة الناقصة إن وجدت)
-- ملاحظة: يتطلب هذا إصدار حديث من PostgreSQL يدعم ADD COLUMN IF NOT EXISTS

-- تحديث جدول الأكسسوارات
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='accessories_prices' AND column_name='category') THEN
    ALTER TABLE accessories_prices ADD COLUMN category TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='accessories_prices' AND column_name='unit') THEN
    ALTER TABLE accessories_prices ADD COLUMN unit TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='accessories_prices' AND column_name='notes') THEN
    ALTER TABLE accessories_prices ADD COLUMN notes TEXT;
  END IF;
END $$;

-- تحديث جدول الألواح
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='boards_settings' AND column_name='board_name') THEN
    ALTER TABLE boards_settings ADD COLUMN board_name TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='boards_settings' AND column_name='code') THEN
    ALTER TABLE boards_settings ADD COLUMN code TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='boards_settings' AND column_name='width') THEN
    ALTER TABLE boards_settings ADD COLUMN width NUMERIC;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='boards_settings' AND column_name='height') THEN
    ALTER TABLE boards_settings ADD COLUMN height NUMERIC;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='boards_settings' AND column_name='cutting_cost_per_cut') THEN
    ALTER TABLE boards_settings ADD COLUMN cutting_cost_per_cut NUMERIC;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='boards_settings' AND column_name='edge_tape_cost_per_meter') THEN
    ALTER TABLE boards_settings ADD COLUMN edge_tape_cost_per_meter NUMERIC;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='boards_settings' AND column_name='notes') THEN
    ALTER TABLE boards_settings ADD COLUMN notes TEXT;
  END IF;
END $$;

-- إنشاء جدول المجموعات
CREATE TABLE IF NOT EXISTS groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- إنشاء جدول الربط بين المستخدمين والمجموعات
CREATE TABLE IF NOT EXISTS user_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  group_id BIGINT REFERENCES groups(id) ON DELETE CASCADE,
  role TEXT DEFAULT 'member', -- 'admin' or 'member'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, group_id)
);

-- تحديث جدول المشاريع
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='user_id') THEN
    ALTER TABLE projects ADD COLUMN user_id UUID REFERENCES auth.users(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='projects' AND column_name='group_id') THEN
    ALTER TABLE projects ADD COLUMN group_id BIGINT REFERENCES groups(id);
  END IF;
END $$;

-- 3. إيقاف RLS (Row Level Security) مؤقتاً
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
ALTER TABLE units DISABLE ROW LEVEL SECURITY;
ALTER TABLE cutting_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE accessories_prices DISABLE ROW LEVEL SECURITY;
ALTER TABLE boards_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE users_profile DISABLE ROW LEVEL SECURITY;

/* 
  -- لترقية مستخدم إلى مدير (Admin)، استبدل البريد الإلكتروني وقم بتشغيل السطر التالي في SQL Editor:
  
  UPDATE public.users_profile 
  SET role = 'admin' 
  WHERE email = 'your-email@example.com';
*/
